/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;


import controladores.ProductoController;
import controladores.ProveedorController;
import java.util.List;
import javax.swing.JOptionPane;
import modelo.dtos.ProductoDTO;
import modelo.dtos.ProveedorDTO;

/**
 *
 * @author llean
 */
public class DialogProducto extends javax.swing.JDialog {
    
    private ProductoController productoController;
    private ProductoDTO productoActual;
    private ProveedorController proveedorController;

    /**
     * Creates new form DialogProducto
     */
    public DialogProducto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.productoController = new ProductoController(this);
        this.proveedorController = new ProveedorController(this);
        initComponents();
        cargarProveedoresEnCombo();
        
        if (this.proveedorController != null) {
            cargarProveedoresEnCombo();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtFilter1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFilter2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtFilter3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtFilter4 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnNew = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Producto");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 40));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Cantidad:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Codigo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        txtFilter1.setBackground(new java.awt.Color(255, 255, 255));
        txtFilter1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtFilter1.setForeground(new java.awt.Color(0, 0, 0));
        txtFilter1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(txtFilter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 460, 40));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nombre:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        txtFilter2.setBackground(new java.awt.Color(255, 255, 255));
        txtFilter2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtFilter2.setForeground(new java.awt.Color(0, 0, 0));
        txtFilter2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(txtFilter2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 230, 40));

        jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TechSupply S.A.", "ElectroMax", "Samsung" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 460, 40));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Categoria:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jComboBox2.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computadoras", "Perifericos", "Monitores", "Audio" }));
        jComboBox2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 460, 40));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Proveedor:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        txtFilter3.setBackground(new java.awt.Color(255, 255, 255));
        txtFilter3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtFilter3.setForeground(new java.awt.Color(0, 0, 0));
        txtFilter3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(txtFilter3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 460, 40));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Precio:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        txtFilter4.setBackground(new java.awt.Color(255, 255, 255));
        txtFilter4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtFilter4.setForeground(new java.awt.Color(0, 0, 0));
        txtFilter4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(txtFilter4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 220, 40));

        jSeparator1.setBackground(new java.awt.Color(153, 161, 175));
        jSeparator1.setForeground(new java.awt.Color(153, 161, 175));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 460, -1));

        btnNew.setBackground(new java.awt.Color(0, 166, 62));
        btnNew.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnNew.setForeground(new java.awt.Color(255, 255, 255));
        btnNew.setText("Guardar");
        btnNew.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 130, 54)));
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        jPanel1.add(btnNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 220, 40));

        btnLogin.setBackground(new java.awt.Color(204, 204, 204));
        btnLogin.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(0, 0, 0));
        btnLogin.setText("Cancelar");
        btnLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 230, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private ProductoDTO construirDto() {
        ProductoDTO dto = new ProductoDTO();

        if (productoActual != null) {
            dto.setIdProducto(productoActual.getIdProducto());
        }

        dto.setCodigo(txtFilter1.getText().trim());
        dto.setNombre(txtFilter3.getText().trim());

        String categoria = (String) jComboBox2.getSelectedItem();
        dto.setCategoria(categoria);

        int proveedorId = obtenerProvId();
        dto.setIdProveedor(proveedorId);

        String precioTexto = txtFilter4.getText().trim();
        if (!precioTexto.isEmpty()) {
            dto.setPrecio(Double.parseDouble(precioTexto));
        } else {
            dto.setPrecio(0.0);
        }

        String cantidadTexto = txtFilter2.getText().trim();
        if (!cantidadTexto.isEmpty()) {
            dto.setStock(Integer.parseInt(cantidadTexto));
        } else {
            dto.setStock(0);
        }

        return dto;
    }
    
    private int obtenerProvId() {
        String nombreProveedor = (String) jComboBox1.getSelectedItem();
            if (nombreProveedor == null) return -1;

            List<ProveedorDTO> coincidencias = proveedorController.buscarPorNombre(nombreProveedor);

            if (coincidencias.isEmpty()) {
                return -1;
            }

            return coincidencias.get(0).getIdProveedor();
    }
    
    public void setProductoActual(ProductoDTO producto) {
    this.productoActual = producto;
    if (productoActual == null) {
        return;
    }

    // Código
    txtFilter1.setText(productoActual.getCodigo());

    // Nombre
    txtFilter3.setText(productoActual.getNombre());

    // Categoría (combo jComboBox2)
    if (productoActual.getCategoria() != null) {
        jComboBox2.setSelectedItem(productoActual.getCategoria());
    }

    // Precio
    txtFilter4.setText(String.valueOf(productoActual.getPrecio()));

    // Cantidad / stock
    txtFilter2.setText(String.valueOf(productoActual.getStock()));

    // Proveedor: asegurar que el combo esté cargado y seleccionar el proveedor
    cargarProveedoresEnCombo();
    cargarComboBoxProveedorDeProducto();
}
    
    private void mostrarErrores(List<String> errores) {
        StringBuilder sb = new StringBuilder("Se encontraron los siguientes errores:\n\n");
        for (String e : errores) {
            sb.append("• ").append(e).append("\n");
        }
        JOptionPane.showMessageDialog(this, sb.toString(),
                "Errores de validación", JOptionPane.WARNING_MESSAGE);
    }
    
    private void cargarProveedoresEnCombo() {
        jComboBox1.removeAllItems();

        List<ProveedorDTO> proveedores = proveedorController.listarTodos();

        for (ProveedorDTO p : proveedores) {
            jComboBox1.addItem(p.getNombre());
        }
    }
    
    private void cargarComboBoxProveedorDeProducto() {
        if (productoActual == null) return;

        int provId = productoActual.getIdProveedor();
        ProveedorDTO prov = proveedorController.obtenerProveedorPorId(provId);

        if (prov == null) return;

        String nombre = prov.getNombre();

        // Find the name in the comboBox and select it
        for (int i = 0; i < jComboBox1.getItemCount(); i++) {
            if (jComboBox1.getItemAt(i).equals(nombre)) {
                jComboBox1.setSelectedIndex(i);
                break;
            }
        }
    }
    
    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        try {
            ProductoDTO dto = construirDto();
            java.util.List<String> errores;

            if (productoActual == null) {
                errores = productoController.crearProducto(dto);
            } else {
                errores = productoController.actualizarProducto(dto);
            }

            if (!errores.isEmpty()) {
                mostrarErrores(errores);
                return;
            }

            JOptionPane.showMessageDialog(this,
                    "Producto guardado correctamente.",
                    "Éxito",
                    JOptionPane.INFORMATION_MESSAGE);

            dispose();

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,
                    "Precio y cantidad deben ser numéricos.",
                    "Error de formato",
                    JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Ocurrió un error al guardar el producto.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        dispose();
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogProducto dialog = new DialogProducto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnNew;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtFilter1;
    private javax.swing.JTextField txtFilter2;
    private javax.swing.JTextField txtFilter3;
    private javax.swing.JTextField txtFilter4;
    // End of variables declaration//GEN-END:variables
}
