/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.CardLayout;
import javax.swing.JButton;
import javax.swing.JFrame;

/**
 *
 * @author llean
 */
public class FrmMenu extends javax.swing.JFrame {
    private MenuGuia controlador;
    private CardLayout cardlayout;
    /**
     * Creates new form FrmProductos
     */
    public FrmMenu() {
        initComponents();
        cardlayout = (CardLayout) panelContenido.getLayout();
        agregarPaneles();
        controlador = new MenuGuia(this);
        mostrarProductos();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }
    
     private void agregarPaneles() {
        panelContenido.add(new PnlProductos(), "PRODUCTOS");
        panelContenido.add(new PnlProveedores(), "PROVEEDORES");
        panelContenido.add(new PnlClientes(), "CLIENTES");
        panelContenido.add(new PnlVentas(), "VENTAS");
        panelContenido.add(new PnlUsuarios(), "USUARIOS");
        panelContenido.add(new PnlFacturas(), "FACTURAS");
    }
    
    public void mostrarProductos() {
        cardlayout.show(panelContenido, "PRODUCTOS");
        marcarBotonActivo(btnProductos);
    }
    
    public void mostrarProveedores() {
        cardlayout.show(panelContenido, "PROVEEDORES");
        marcarBotonActivo(btnProveedores);
    }
    
    public void mostrarClientes() {
        cardlayout.show(panelContenido, "CLIENTES");
        marcarBotonActivo(btnClientes);
    }
    
    public void mostrarVentas() {
        cardlayout.show(panelContenido, "VENTAS");
        marcarBotonActivo(btnVentas);
    }
    
    public void mostrarUsuarios() {
        cardlayout.show(panelContenido, "USUARIOS");
        marcarBotonActivo(btnUsuarios);
    }
    
    public void mostrarFacturas() {
        cardlayout.show(panelContenido, "FACTURAS");
        marcarBotonActivo(btnFacturas);
    }
    
    private JButton botonActivo = null;
    private void marcarBotonActivo(JButton boton) {
        if (botonActivo != null && botonActivo != btnLogout) {
            botonActivo.setBackground(new java.awt.Color(52, 73, 94));
        }

        if (boton != btnLogout) {
            boton.setBackground(new java.awt.Color(41, 128, 185));
            botonActivo = boton;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnLogout = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnProveedores = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnFacturas = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        panelContenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 800));
        setMinimumSize(new java.awt.Dimension(1200, 800));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(30, 41, 57));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 500));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/StepDownIconSmall.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 50));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 180, 70));

        jSeparator1.setBackground(new java.awt.Color(54, 65, 83));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 730, 180, 10));

        btnLogout.setBackground(new java.awt.Color(231, 0, 11));
        btnLogout.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Cerrar Sesión ");
        btnLogout.setAlignmentX(0.5F);
        btnLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(193, 0, 7)));
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogout.setIconTextGap(5);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 750, 180, 40));

        btnProductos.setBackground(new java.awt.Color(21, 93, 252));
        btnProductos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnProductos.setForeground(new java.awt.Color(255, 255, 255));
        btnProductos.setText("Productos");
        btnProductos.setAlignmentX(0.5F);
        btnProductos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255)));
        btnProductos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProductos.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnProductos.setIconTextGap(5);
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        jPanel2.add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 180, 40));

        btnProveedores.setBackground(new java.awt.Color(54, 65, 83));
        btnProveedores.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnProveedores.setForeground(new java.awt.Color(255, 255, 255));
        btnProveedores.setText("Proveedores");
        btnProveedores.setAlignmentX(0.5F);
        btnProveedores.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 85, 101)));
        btnProveedores.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProveedores.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnProveedores.setIconTextGap(5);
        btnProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedoresActionPerformed(evt);
            }
        });
        jPanel2.add(btnProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 180, 40));

        btnClientes.setBackground(new java.awt.Color(54, 65, 83));
        btnClientes.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnClientes.setForeground(new java.awt.Color(255, 255, 255));
        btnClientes.setText("Clientes");
        btnClientes.setAlignmentX(0.5F);
        btnClientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 85, 101)));
        btnClientes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnClientes.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnClientes.setIconTextGap(5);
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        jPanel2.add(btnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 180, 40));

        btnVentas.setBackground(new java.awt.Color(54, 65, 83));
        btnVentas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnVentas.setForeground(new java.awt.Color(255, 255, 255));
        btnVentas.setText("Ventas");
        btnVentas.setAlignmentX(0.5F);
        btnVentas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 85, 101)));
        btnVentas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVentas.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnVentas.setIconTextGap(5);
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });
        jPanel2.add(btnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 180, 40));

        btnUsuarios.setBackground(new java.awt.Color(54, 65, 83));
        btnUsuarios.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setText("Usuarios");
        btnUsuarios.setAlignmentX(0.5F);
        btnUsuarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 85, 101)));
        btnUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnUsuarios.setIconTextGap(5);
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        jPanel2.add(btnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 180, 40));

        btnFacturas.setBackground(new java.awt.Color(54, 65, 83));
        btnFacturas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnFacturas.setForeground(new java.awt.Color(255, 255, 255));
        btnFacturas.setText("Facturas");
        btnFacturas.setAlignmentX(0.5F);
        btnFacturas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(74, 85, 101)));
        btnFacturas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnFacturas.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnFacturas.setIconTextGap(5);
        btnFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturasActionPerformed(evt);
            }
        });
        jPanel2.add(btnFacturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 180, 40));

        jSeparator2.setBackground(new java.awt.Color(54, 65, 83));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 103, 180, 10));

        getContentPane().add(jPanel2, java.awt.BorderLayout.WEST);

        panelContenido.setPreferredSize(new java.awt.Dimension(990, 790));
        panelContenido.setLayout(new java.awt.CardLayout());
        getContentPane().add(panelContenido, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        mostrarProductos();
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedoresActionPerformed
        mostrarProveedores();
    }//GEN-LAST:event_btnProveedoresActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        mostrarClientes();
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        mostrarVentas();
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        mostrarUsuarios();
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturasActionPerformed
        mostrarFacturas();
    }//GEN-LAST:event_btnFacturasActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
       controlador.cerrarSesion();
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnFacturas;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnProveedores;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JButton btnVentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel panelContenido;
    // End of variables declaration//GEN-END:variables
}
