/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import modelo.dtos.ProveedorDTO;
import modelo.servicios.ProveedorService;

/**
 *
 * @author llean
 */
public class PnlProveedores extends javax.swing.JPanel {
    
    private DefaultTableModel tableModel;
    private ProveedorService proveedorService;

    /**
     * Creates new form PnlProveedores
     */
    public PnlProveedores() {
        initComponents();
        inicializar();
        cargarDatos();
    }
    
    private void inicializar() {
        String[] columnas = {"ID", "Nombre", "Contacto", "Dirección"};
        tableModel = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        jTable1.setModel(tableModel);

        jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);   // ID
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(200);  // Nombre
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(200);  // Contacto
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(300);  // Dirección

        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        proveedorService = new ProveedorService();
    }
    
    private void cargarDatos() {
        try {
            List<ProveedorDTO> proveedores = proveedorService.listarTodos();
            actualizarTabla(proveedores);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al cargar proveedores: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void actualizarTabla(List<ProveedorDTO> proveedores) {
        tableModel.setRowCount(0);

        for (ProveedorDTO p : proveedores) {
            Object[] fila = {
                p.getIdProveedor(),
                p.getNombre(),
                p.getContacto(),
                p.getDireccion()
            };
            tableModel.addRow(fila);
        }

        tableModel.fireTableDataChanged();
    }
    
    private ProveedorDTO obtenerProveedorDeFila(int row) {
        ProveedorDTO dto = new ProveedorDTO();
        dto.setIdProveedor((Integer) tableModel.getValueAt(row, 0));
        dto.setNombre((String) tableModel.getValueAt(row, 1));
        dto.setContacto((String) tableModel.getValueAt(row, 2));
        dto.setDireccion((String) tableModel.getValueAt(row, 3));
        return dto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblGestion = new javax.swing.JLabel();
        txtFilter = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        table = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnNew = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1200, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 161, 175)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblGestion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblGestion.setForeground(new java.awt.Color(30, 41, 57));
        lblGestion.setText("Gestion de Proveedores");
        jPanel4.add(lblGestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 19, -1, -1));

        txtFilter.setBackground(new java.awt.Color(255, 255, 255));
        txtFilter.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtFilter.setForeground(new java.awt.Color(0, 0, 0));
        txtFilter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 161, 175)));
        txtFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFilterActionPerformed(evt);
            }
        });
        jPanel4.add(txtFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 670, 40));

        btnDelete.setBackground(new java.awt.Color(231, 0, 11));
        btnDelete.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Eliminar");
        btnDelete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 130, 54)));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel4.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 50, 80, 40));

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.setViewportView(jTable1);

        jPanel4.add(table, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 940, 660));

        btnNew.setBackground(new java.awt.Color(0, 166, 62));
        btnNew.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnNew.setForeground(new java.awt.Color(255, 255, 255));
        btnNew.setText("Nuevo");
        btnNew.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 130, 54)));
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        jPanel4.add(btnNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 50, 80, 40));

        btnEdit.setBackground(new java.awt.Color(21, 93, 252));
        btnEdit.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Editar");
        btnEdit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 130, 54)));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel4.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 50, 80, 40));

        jPanel5.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 980, 780));

        add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 800));
    }// </editor-fold>//GEN-END:initComponents

    private void txtFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFilterActionPerformed
        String criterio = txtFilter.getText().trim().toLowerCase();

        if (criterio.isEmpty()) {
            cargarDatos();
            return;
        }

        try {
            List<ProveedorDTO> proveedores = proveedorService.listarTodos();
            List<ProveedorDTO> filtrados = new ArrayList<>();

            for (ProveedorDTO p : proveedores) {
                String nombre = p.getNombre() != null ? p.getNombre().toLowerCase() : "";
                String contacto = p.getContacto() != null ? p.getContacto().toLowerCase() : "";

                if (nombre.contains(criterio) || contacto.contains(criterio)) {
                    filtrados.add(p);
                }
            }

            actualizarTabla(filtrados);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al buscar proveedores: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtFilterActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        java.awt.Frame parent = (java.awt.Frame) SwingUtilities.getWindowAncestor(this);
        DialogProveedor dialog = new DialogProveedor(parent, true);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        cargarDatos();
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this,
                    "Por favor, seleccione un proveedor de la tabla",
                    "Advertencia",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        ProveedorDTO proveedor = obtenerProveedorDeFila(selectedRow);

        java.awt.Frame parent = (java.awt.Frame) SwingUtilities.getWindowAncestor(this);
        DialogProveedor dialog = new DialogProveedor(parent, true);
        dialog.setProveedorActual(proveedor);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);

        cargarDatos();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this,
                    "Por favor, seleccione un proveedor de la tabla",
                    "Advertencia",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        int opcion = JOptionPane.showConfirmDialog(this,
                "¿Está seguro de que desea eliminar el proveedor seleccionado?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);

        if (opcion != JOptionPane.YES_OPTION) {
            return;
        }

        ProveedorDTO proveedor = obtenerProveedorDeFila(selectedRow);

        boolean ok = proveedorService.eliminarProveedor(proveedor.getIdProveedor());
        if (!ok) {
            JOptionPane.showMessageDialog(this,
                    "No se pudo eliminar el proveedor.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            cargarDatos();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnNew;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblGestion;
    private javax.swing.JScrollPane table;
    private javax.swing.JTextField txtFilter;
    // End of variables declaration//GEN-END:variables
}
