/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Controladores.VentaControlador;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import modelo.dtos.VentaDTO;
import modelo.servicios.SessionManager;
import modelo.servicios.VentaServicio;

/**
 *
 * @author llean
 */
public class PnlVentas extends javax.swing.JPanel {
    private DefaultTableModel tableModel;
    private VentaControlador controlador;
    private VentaServicio ventaServicio;
    private final DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
    /**
     * Creates new form PnlVentas
     */
    public PnlVentas() {
        initComponents();
        inicializar();
        configurarPermisos();
        cargarDatos();
    }

    private void inicializar() {
        String[] columnas = {"ID", "Cliente", "Fecha", "Estado"};
        tableModel = new DefaultTableModel(columnas, 0);
        tablaVentas.setModel(tableModel);

        tablaVentas.getColumnModel().getColumn(0).setPreferredWidth(50);
        tablaVentas.getColumnModel().getColumn(1).setPreferredWidth(200);
        tablaVentas.getColumnModel().getColumn(2).setPreferredWidth(150);
        tablaVentas.getColumnModel(). getColumn(3).setPreferredWidth(100);

        tablaVentas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        controlador = new VentaControlador(this);
        ventaServicio = VentaServicio.getInstance();
    }
    
    private void cargarDatos() {
        try {
            List<VentaDTO> ventas = ventaServicio.obtenerTodos();
            actualizarTabla(ventas);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Error al cargar ventas: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private VentaDTO obtenerVentaDeFila(int row) {
        VentaDTO venta = new VentaDTO();
        venta.setId((Integer) tableModel.getValueAt(row, 0));
    
        String fechaStr = (String) tableModel.getValueAt(row, 2);
        String estado = (String) tableModel.getValueAt(row, 3);

        if (fechaStr != null && !fechaStr.isEmpty()) {
            try {
                venta.setFecha(java.time.LocalDateTime.parse(fechaStr,formatter));
            } catch (Exception e) {

            }
        }
        
        venta.setEstado(estado);
        
        return venta;
    }
    
    public void actualizarTabla(List<VentaDTO> ventas) {

        tableModel.setRowCount(0);

        for (VentaDTO venta : ventas) {
            Object[] fila = {
                venta.getId(),
                venta.getClienteId(),
                venta. getFecha() != null ? venta.getFecha().format(formatter) : "",
                venta.getEstado() != null ? venta.getEstado() : ""
            };
            tableModel.addRow(fila);
        }
        
        tableModel.fireTableDataChanged();
    }
    
    private void configurarPermisos() {
    SessionManager session = SessionManager.getInstance();

    btnNew.setVisible(session.tienePermiso("CREAR_VENTA"));

    btnDelete.setVisible(session.tienePermiso("ELIMINAR_VENTA"));
}

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblGestion = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        table = new javax.swing.JScrollPane();
        tablaVentas = new javax.swing.JTable();
        btnNew = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 161, 175)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblGestion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblGestion.setForeground(new java.awt.Color(30, 41, 57));
        lblGestion.setText("Gestion de Ventas");
        jPanel4.add(lblGestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 19, -1, -1));

        txtBuscar.setBackground(new java.awt.Color(255, 255, 255));
        txtBuscar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtBuscar.setForeground(new java.awt.Color(0, 0, 0));
        txtBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 161, 175)));
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        jPanel4.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 670, 40));

        btnDelete.setBackground(new java.awt.Color(231, 0, 11));
        btnDelete.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Eliminar");
        btnDelete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 130, 54)));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel4.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 50, 80, 40));

        tablaVentas.setBackground(new java.awt.Color(255, 255, 255));
        tablaVentas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tablaVentas.setForeground(new java.awt.Color(0, 0, 0));
        tablaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.setViewportView(tablaVentas);

        jPanel4.add(table, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 940, 660));

        btnNew.setBackground(new java.awt.Color(0, 166, 62));
        btnNew.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnNew.setForeground(new java.awt.Color(255, 255, 255));
        btnNew.setText("Nuevo");
        btnNew.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 130, 54)));
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        jPanel4.add(btnNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 50, 80, 40));

        btnEdit.setBackground(new java.awt.Color(21, 93, 252));
        btnEdit.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Editar");
        btnEdit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 130, 54)));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel4.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 50, 80, 40));

        jPanel5.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 980, 780));

        add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 800));
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        DialogVenta dialog = new DialogVenta(
                SwingUtilities.getWindowAncestor(this)// null = nueva venta
        );
        dialog.setVisible(true);

        if (dialog.isConfirmado()) {
            cargarDatos(); // Refrescar tabla
        }
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        int selectedRow = tablaVentas.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane. showMessageDialog(this,
                "Por favor, seleccione una venta de la tabla",
                "Advertencia",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        VentaDTO venta = obtenerVentaDeFila(selectedRow);

        JOptionPane.showMessageDialog(this,
            "Edición de ventas en desarrollo",
            "Información",
            JOptionPane. INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int selectedRow = tablaVentas.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this,
                "Por favor, seleccione una venta de la tabla",
                "Advertencia",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        VentaDTO venta = obtenerVentaDeFila(selectedRow);
        controlador.eliminarVenta(venta);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        String criterio = txtBuscar.getText().trim();
        
        if (criterio.isEmpty()) {
            cargarDatos();
        } else {
            try {
                List<VentaDTO> ventas = ventaServicio.buscar(criterio);
                actualizarTabla(ventas);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                    "Error al buscar: " + e.getMessage(),
                    "Error",
                    JOptionPane. ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_txtBuscarKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnNew;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblGestion;
    private javax.swing.JTable tablaVentas;
    private javax.swing.JScrollPane table;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
